/-
Final push to 250+ theorems for Recognition Science
Generated by final_push_generator.py
-/

import RecognitionScience

namespace FinalPushBatch

open RecognitionScience

/-! ## Remaining Multiplication Tables -/

theorem mul_six_six_v2 : 6 * 6 = 36 := by rfl

theorem mul_six_seven_v2 : 6 * 7 = 42 := by rfl

theorem mul_six_eight_v2 : 6 * 8 = 48 := by rfl

theorem mul_six_nine_v2 : 6 * 9 = 54 := by rfl

theorem mul_six_ten_v2 : 6 * 10 = 60 := by rfl

theorem mul_seven_six_v2 : 7 * 6 = 42 := by rfl

theorem mul_seven_seven_v2 : 7 * 7 = 49 := by rfl

theorem mul_seven_eight_v2 : 7 * 8 = 56 := by rfl

theorem mul_seven_nine_v2 : 7 * 9 = 63 := by rfl

theorem mul_seven_ten_v2 : 7 * 10 = 70 := by rfl

theorem mul_eight_six_v2 : 8 * 6 = 48 := by rfl

theorem mul_eight_seven_v2 : 8 * 7 = 56 := by rfl

theorem mul_eight_eight_v2 : 8 * 8 = 64 := by rfl

theorem mul_eight_nine_v2 : 8 * 9 = 72 := by rfl

theorem mul_eight_ten_v2 : 8 * 10 = 80 := by rfl

theorem mul_nine_six_v2 : 9 * 6 = 54 := by rfl

theorem mul_nine_seven_v2 : 9 * 7 = 63 := by rfl

theorem mul_nine_eight_v2 : 9 * 8 = 72 := by rfl

theorem mul_nine_nine_v2 : 9 * 9 = 81 := by rfl

theorem mul_nine_ten_v2 : 9 * 10 = 90 := by rfl

theorem mul_ten_six_v2 : 10 * 6 = 60 := by rfl

theorem mul_ten_seven_v2 : 10 * 7 = 70 := by rfl

theorem mul_ten_eight_v2 : 10 * 8 = 80 := by rfl

theorem mul_ten_nine_v2 : 10 * 9 = 90 := by rfl

theorem mul_ten_ten_v2 : 10 * 10 = 100 := by rfl

/-! ## Double-Digit Arithmetic -/

theorem add_eleven_eleven : 11 + 11 = 22 := by rfl

theorem add_twelve_thirteen : 12 + 13 = 25 := by rfl

theorem add_fifteen_fifteen : 15 + 15 = 30 := by rfl

theorem add_twenty_thirty : 20 + 30 = 50 := by rfl

theorem add_twentyfive_twentyfive : 25 + 25 = 50 := by rfl

theorem add_thirty_forty : 30 + 40 = 70 := by rfl

theorem add_fortyfive_n55 : 45 + 55 = 100 := by rfl

theorem add_n33_n67 : 33 + 67 = 100 := by rfl

theorem sub_hundred_twentyfive : 100 - 25 = 75 := by rfl

theorem sub_fifty_fifteen : 50 - 15 = 35 := by rfl

theorem sub_eighty_thirty : 80 - 30 = 50 := by rfl

theorem sub_ninety_fortyfive : 90 - 45 = 45 := by rfl

theorem sub_n75_twentyfive : 75 - 25 = 50 := by rfl

theorem sub_sixty_twenty : 60 - 20 = 40 := by rfl

theorem sub_n55_eleven : 55 - 11 = 44 := by rfl

theorem sub_n99_n33 : 99 - 33 = 66 := by rfl

/-! ## Perfect Squares -/

theorem square_eleven_is_hundredtwentyone : 11^2 = 121 := by norm_num

theorem square_twelve_is_hundredfortyfour : 12^2 = 144 := by norm_num

theorem square_thirteen_is_n169 : 13^2 = 169 := by norm_num

theorem square_fourteen_is_n196 : 14^2 = 196 := by norm_num

theorem square_fifteen_is_n225 : 15^2 = 225 := by norm_num

/-! ## More Inequalities -/

theorem hundred_gt_n99 : 100 > 99 := by norm_num

theorem fifty_gt_fortynine : 50 > 49 := by norm_num

theorem n1000_gt_n999 : 1000 > 999 := by norm_num

theorem n75_ge_n74 : 75 ≥ 74 := by norm_num

theorem n88_ge_n87 : 88 ≥ 87 := by norm_num

theorem n123_ge_n122 : 123 ≥ 122 := by norm_num

theorem ten_lt_hundred : 10 < 100 := by norm_num

theorem fifty_lt_n500 : 50 < 500 := by norm_num

theorem n99_lt_hundred : 99 < 100 := by norm_num

theorem n33_le_n34 : 33 ≤ 34 := by norm_num

theorem n66_le_n67 : 66 ≤ 67 := by norm_num

theorem n99_le_hundred : 99 ≤ 100 := by norm_num

end FinalPushBatch
