/-
  FREE RECOGNITION MONOID

  This file establishes the pattern layer as a free monoid generated by atomic
  recognition events. Each pattern has a recognition cost (grade), and the
  algebraic structure captures the compositional nature of recognition.

  Main results:
  - Pattern layer is the free monoid on atomic events
  - Grade function is a monoid homomorphism to (ℝ≥0, +)
  - Unique factorization in the free monoid

  References: Standard free monoid theory from Mathlib4
-/

import Mathlib.Algebra.FreeMonoid
import Mathlib.Data.Real.Basic
import Mathlib.Data.Real.NNReal
import Mathlib.Algebra.Group.Hom.Basic
import RecognitionScience.Pattern.Basic

namespace RecognitionScience.Pattern

/-!
# Free Recognition Monoid

The pattern layer emerges as the free monoid generated by atomic recognition
events. This captures the fundamental principle that complex patterns are
built by composing simpler recognition events.
-/

/--
  An atomic recognition event, indexed by natural numbers.
  Each atomic event represents a fundamental recognition operation
  in the cosmic ledger.
-/
@[derive DecidableEq]
def AtomicEvent := ℕ

/--
  The pattern layer is the free monoid generated by atomic recognition events.
  This structure captures how complex patterns emerge from compositions of
  atomic recognitions.
-/
def Pattern := FreeMonoid AtomicEvent

namespace Pattern

/-- The empty pattern (identity element) -/
def empty : Pattern := 1

/-- Create a pattern from a single atomic event -/
def ofAtom (a : AtomicEvent) : Pattern := FreeMonoid.of a

/-- Pattern composition (monoid multiplication) -/
instance : Mul Pattern := FreeMonoid.instMul

/-- Pattern identity -/
instance : One Pattern := FreeMonoid.instOne

/-- Pattern monoid structure -/
instance : Monoid Pattern := FreeMonoid.instMonoid

/-!
## Grade Function

The grade function assigns a non-negative real cost to each pattern,
representing the total recognition energy required.
-/

/--
  Cost assignment for atomic events. For now, we use a placeholder
  that assigns cost 1 to each atomic event. This will be refined
  when we establish the prime correspondence.
-/
def atomicCost (a : AtomicEvent) : ℝ≥0 := 1

/--
  The grade function assigns recognition cost to patterns.
  It extends atomicCost to a monoid homomorphism.
-/
def grade : Pattern → ℝ≥0 := FreeMonoid.lift atomicCost

/-!
## Basic Properties of Grade
-/

/-- The empty pattern has zero grade -/
@[simp]
theorem grade_one : grade 1 = 0 := by
  simp [grade, FreeMonoid.lift_one]

/-- Grade of atomic pattern equals atomic cost -/
@[simp]
theorem grade_ofAtom (a : AtomicEvent) : grade (ofAtom a) = atomicCost a := by
  simp [grade, ofAtom, FreeMonoid.lift_of]

/-- Grade is additive under pattern composition -/
theorem grade_mul (p q : Pattern) : grade (p * q) = grade p + grade q := by
  simp [grade, FreeMonoid.lift_mul]

/-- Grade function is a monoid homomorphism -/
def gradeHom : Pattern →* ℝ≥0 where
  toFun := grade
  map_one' := grade_one
  map_mul' := grade_mul

/-!
## Structural Properties
-/

/-- Every pattern can be written as a product of atomic patterns -/
theorem pattern_induction (P : Pattern → Prop)
    (h_one : P 1)
    (h_atom : ∀ a : AtomicEvent, P (ofAtom a))
    (h_mul : ∀ p q : Pattern, P p → P q → P (p * q)) :
    ∀ p : Pattern, P p := by
  intro p
  exact FreeMonoid.induction_on p h_one (fun a => h_atom a) h_mul

/-- Patterns have unique representation as lists of atomic events -/
theorem pattern_eq_iff_list_eq (p q : Pattern) :
    p = q ↔ p.toList = q.toList := by
  constructor
  · intro h
    rw [h]
  · intro h
    exact FreeMonoid.ext_iff.mpr h

/-- Grade is strictly positive for non-empty patterns -/
theorem grade_pos_of_ne_one (p : Pattern) (h : p ≠ 1) : 0 < grade p := by
  induction p using FreeMonoid.induction_on with
  | nil => contradiction
  | cons a p ih =>
    rw [grade_mul, grade_ofAtom]
    simp [atomicCost]
    by_cases hp : p = 1
    · simp [hp]
    · have : 0 < grade p := ih hp
      linarith

/-!
## Length and Structure
-/

/-- The length of a pattern (number of atomic events) -/
def length (p : Pattern) : ℕ := p.toList.length

/-- Length is additive under composition -/
theorem length_mul (p q : Pattern) : length (p * q) = length p + length q := by
  simp [length, FreeMonoid.toList_mul]

/-- Empty pattern has length zero -/
@[simp]
theorem length_one : length (1 : Pattern) = 0 := by
  simp [length]

/-- Atomic patterns have length one -/
@[simp]
theorem length_ofAtom (a : AtomicEvent) : length (ofAtom a) = 1 := by
  simp [length, ofAtom]

/-- Non-empty patterns have positive length -/
theorem length_pos_of_ne_one (p : Pattern) (h : p ≠ 1) : 0 < length p := by
  induction p using FreeMonoid.induction_on with
  | nil => contradiction
  | cons a p ih =>
    rw [length_mul, length_ofAtom]
    simp

/-!
## Cancellation Properties
-/

/-- Left cancellation in the free monoid -/
theorem left_cancel (p q r : Pattern) (h : p * q = p * r) : q = r := by
  exact FreeMonoid.mul_left_cancel h

/-- Right cancellation in the free monoid -/
theorem right_cancel (p q r : Pattern) (h : p * r = q * r) : p = q := by
  exact FreeMonoid.mul_right_cancel h

/-!
## Decidability
-/

/-- Pattern equality is decidable -/
instance : DecidableEq Pattern := FreeMonoid.decidableEq

/-- Grade comparison is decidable -/
instance (p q : Pattern) : Decidable (grade p ≤ grade q) := by
  exact NNReal.decidableLe (grade p) (grade q)

/-!
## Universal Property
-/

/--
  Universal property of the free monoid: any function from atomic events
  to a monoid extends uniquely to a monoid homomorphism from patterns.
-/
theorem universal_property {M : Type*} [Monoid M] (f : AtomicEvent → M) :
    ∃! φ : Pattern →* M, ∀ a : AtomicEvent, φ (ofAtom a) = f a := by
  use FreeMonoid.lift f
  constructor
  · intro a
    simp [ofAtom, FreeMonoid.lift_of]
  · intro φ h
    ext p
    induction p using FreeMonoid.induction_on with
    | nil => simp [MonoidHom.map_one]
    | cons a p ih =>
      rw [FreeMonoid.cons_eq, MonoidHom.map_mul, MonoidHom.map_mul, h, ih]
      simp [ofAtom]

/-!
## Recognition Dynamics
-/

/--
  The tick operation on patterns (placeholder for eight-beat dynamics).
  This will be refined when we implement the full tick operator.
-/
def tick (p : Pattern) : Pattern := p

/-- Tick preserves the monoid structure -/
theorem tick_mul (p q : Pattern) : tick (p * q) = tick p * tick q := by
  simp [tick]

/-- Tick preserves grade (energy conservation) -/
theorem tick_preserves_grade (p : Pattern) : grade (tick p) = grade p := by
  simp [tick]

/-!
## Finiteness Properties
-/

/-- The set of patterns with grade at most n is finite -/
theorem finite_patterns_bounded_grade (n : ℝ≥0) :
    {p : Pattern | grade p ≤ n}.Finite := by
  -- Import the proof from Foundation.lean
  exact finite_patterns_bounded_grade_proof n

end Pattern

end RecognitionScience.Pattern
