name: Lean Verification

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install elan
      run: |
        curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    
    - name: Get Lean version
      run: |
        lean --version
        lake --version
    
    - name: Cache .lake
      uses: actions/cache@v3
      with:
        path: .lake
        key: ${{ runner.os }}-lake-${{ hashFiles('lakefile.lean') }}
    
    - name: Build project
      run: lake build
    
    - name: Check for sorries
      run: |
        echo "Checking for 'sorry' in Lean files..."
        if find . -name "*.lean" -type f ! -path "./foundation/*" ! -path "./archive*/*" -exec grep -l "sorry" {} \; | grep .; then
          echo "❌ Found 'sorry' in Lean files!"
          exit 1
        else
          echo "✅ No 'sorry' found in Lean files"
        fi
    
    - name: Check for .DS_Store files
      run: |
        echo "Checking for .DS_Store files..."
        if find . -name ".DS_Store" -type f | grep .; then
          echo "❌ Found .DS_Store files! These should not be committed."
          exit 1
        else
          echo "✅ No .DS_Store files found"
        fi
    
    - name: Check for unauthorized axioms
      run: |
        echo "Checking for axioms outside allowed files..."
        # Allowed axioms are only in these files
        ALLOWED_FILES="formal/Axioms.lean|Quantum/BandwidthCost.lean|Cosmology/BandwidthLambda.lean"
        
        # Find all axioms
        if grep -r "^axiom" --include="*.lean" . | grep -v "^./foundation/" | grep -vE "($ALLOWED_FILES)"; then
          echo "❌ Found unauthorized axioms!"
          exit 1
        else
          echo "✅ All axioms are in authorized locations"
        fi
    
    - name: Count axioms
      run: |
        echo "Counting total axioms..."
        AXIOM_COUNT=$(find . -name "*.lean" -type f ! -path "./foundation/*" ! -path "./archive*/*" -exec grep -l "^axiom" {} \; | wc -l)
        echo "Total axioms in gravity: $AXIOM_COUNT"
        
        if [ $AXIOM_COUNT -gt 2 ]; then
          echo "❌ Too many axioms! Expected 2, found $AXIOM_COUNT"
          exit 1
        else
          echo "✅ Axiom count is acceptable"
        fi 